backend:
  name: git-gateway
  repo: araujofelipebr/felipearaujocoach # Branch to update (optional; defaults to master)
  branch: gh-pages
  site-domain: zen-khorana-fe1453.netfly.com

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
collections: 
  - name: "pages"
    label: "pagina"
    folder: "/"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}

